### ISSUE TITLE
PM Review #2: User Authentication

### ISSUE THREAD

**Issue by andrewlangston** [bhanu-gupta/funbook#2]
Bhanu - 

Excellent job with your user auth. A few points to be addressed this weekend, as we discussed:
- [x] Some CSS tweaks are necessary to the forms you render after a user unsuccessfully signs up or logs in
- [x] Eventually, you will want to display error tooltips immediately upon unsuccessful sign up (rather than waiting for a user to focus on a specific input field to display the corresponding error).

Please take some time addressing these before moving on to user profiles, friending, and posts. Slack me if you have any questions!

**Comment by bhanu-gupta** [comment]
Thanks for your feedback Andrew. I have fixed the above issues.
